server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  data:
    redis:
      host: localhost
      port: 6370
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000
